-- 삭제관리

-- 테이블 삭제
DROP TABLE "USERS" CASCADE CONSTRAINTS;
DROP TABLE "DOG" CASCADE CONSTRAINTS;
DROP TABLE "WALKLOG" CASCADE CONSTRAINTS;
DROP TABLE "COORDS" CASCADE CONSTRAINTS;
DROP TABLE "BLOG" CASCADE CONSTRAINTS;
DROP TABLE "IMAGES" CASCADE CONSTRAINTS;
DROP TABLE "CLUB" CASCADE CONSTRAINTS;
DROP TABLE "CLUBUSERS" CASCADE CONSTRAINTS;
DROP TABLE "MEETING" CASCADE CONSTRAINTS;
DROP TABLE "MEETINGINFO" CASCADE CONSTRAINTS;
DROP TABLE "CLUBBOARDCATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "WALKEDDOG" CASCADE CONSTRAINTS;
DROP TABLE "TRAIL" CASCADE CONSTRAINTS;
DROP TABLE "TRAILUSED" CASCADE CONSTRAINTS;
DROP TABLE "TRAILSTAR" CASCADE CONSTRAINTS;
DROP TABLE "TRAILCMT" CASCADE CONSTRAINTS;
DROP TABLE "TRAILTAG" CASCADE CONSTRAINTS;
DROP TABLE "WALKLOGCMT" CASCADE CONSTRAINTS;
DROP TABLE "COMMBOARD" CASCADE CONSTRAINTS;
DROP TABLE "COMMCMT" CASCADE CONSTRAINTS;
DROP TABLE "FOLLOW" CASCADE CONSTRAINTS;
DROP TABLE "FRIEND" CASCADE CONSTRAINTS;
DROP TABLE "CLUBJOIN" CASCADE CONSTRAINTS;
DROP TABLE "COMPLAINTS" CASCADE CONSTRAINTS;
DROP TABLE "LOCATION" CASCADE CONSTRAINTS;
DROP TABLE "CLUBBOARD" CASCADE CONSTRAINTS;
DROP TABLE "CLUBCMT" CASCADE CONSTRAINTS;
DROP TABLE "USERLIKE" CASCADE CONSTRAINTS;

-- 시퀀스 삭제
Begin
for c in (SELECT * FROM all_sequences WHERE SEQUENCE_OWNER='RUNNINGDOG') loop
  execute immediate 'drop SEQUENCE '||c.sequence_name;
end loop;
End;